### ISSUE TITLE
Screen Capture does not update

### ISSUE THREAD

**Issue by davidqian88** [nopeAnon/Automated-HoloCure-Fishing#34]
Hi,
The screen capture doesn't update when running. Restarting the script doesn't help. It update's when the program is closed or switching the capture to a different program. I tried reinstalling the environment and updating to python 3.11.5.
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/32712154/710f0a36-7f0b-4696-aaf7-1ef30206699f)
If I started the script before HoloCure, then it will capture something in the background.
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/32712154/071926e1-dcd5-4d1c-ac52-120c43927ea8)
I don't think the capture_game would leave any cache. But it seems like that way.

**Comment by nopeAnon** [comment]
> It update's when the program is closed or switching the capture to a different program.

That wouldn't make sense. It shouldn't do anything when it's closed. https://github.com/nopeAnon/Automated-HoloCure-Fishing/blob/90da42e5bd12beeacf897f056b91edfe197cbda6/holocure_fishing.py#L46-L48

And it shouldn't even switch programs, since there should only be one application with the window class  `YYGameMakerYY` and title `HoloCure` https://github.com/nopeAnon/Automated-HoloCure-Fishing/blob/90da42e5bd12beeacf897f056b91edfe197cbda6/holocure_fishing.py#L45
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/91358729/0a8ed870-7731-4326-99f9-7fc7e5a7b811)

Can you try running the script again with all windows closed except holocure?

**Comment by davidqian88** [comment]
This is what I got after closing the browser and launch the game before running the script. I was switching the capture window in the script manually to check if it is looking for the correct window.
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/32712154/0ae74f05-7ee8-4133-a349-7bcc21ba9378)

**Comment by davidqian88** [comment]
> It update's when the program is closed or switching the capture to a different program.

The screenshot "resets" when I run the script without opening the HoloCure. The screenshot will stay the same when I stop the script and HolocCure and run the script after HoloCure is launched or if I stop the script and re-run while HoloCure is running.

**Comment by Hexus-One** [comment]
Hi it looks like you're on Windows 11 - I wrote and tested the code on Windows 10 only (using VS Code) so I'm not sure how it would behave on Win11. Does the program still work regardless of the debug window display?

**Comment by davidqian88** [comment]
> Does the program still work regardless of the debug window display?

Unfortunately it’s not. I’ll try the timer you mentioned in issue 21.

**Comment by nopeAnon** [comment]
See #38 tldr: Disable fullscreen optimizations in holocure.exe
