### ISSUE TITLE
game not responding issue

### ISSUE THREAD

**Issue by KayCen0w0** [nopeAnon/Automated-HoloCure-Fishing#6]
Around 12.p.m, the program worked successfully, and the game did start to fish automatically, but there was a time response problem mentioned in other issues, but after the next update, the program did detect the symbol and successfully displayed wasd, but the game No response. I don't know why it happens.
![image](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/142689383/6fb5cca1-87d3-4e30-b920-3f5ae36fe66f)

**Comment by zackszackz** [comment]
yup, that's my problem too

**Comment by zackszackz** [comment]
the code was runnin, but in the game it didn't.. in my case the code was work only in yellow ! .. in orange, red, or super red the game was failed to response, but the code was runnin.

**Comment by MichaelC03** [comment]
The issue is the placement of the region where the arrows are being seen; it's too far to the left, causing the program to input the direction before it's actually enough in the circle for HoloCure to detect it as a successful "hit". You can easily fix this by opening up the holocure_fishing.py file and messing with the region variable (on line 102). I personally just changed the starting left point from hit_area.left+14 to hit_area.left+20.

That is, I changed the line from
`region = (hit_area.left+14, hit_area.top+24, hit_area.width-16, hit_area.height-30)`
to
`region = (hit_area.left+20, hit_area.top+24, hit_area.width-16, hit_area.height-30)`

This solved the issue for me. Hope that helps!

**Comment by zackszackz** [comment]
omg, problem solved.. thanks @MichaelC03

**Comment by KayCen0w0** [comment]
> the code was runnin, but in the game it didn't.. in my case the code was work only in yellow ! .. in orange, red, or super red the game was failed to response, but the code was runnin.

In my case, whatever triggers the exclamation point is unresponsive, and then trying to change it still the same.

**Comment by KayCen0w0** [comment]
Ok, I don't know why it worked after I re-downloaded python.
